parameters:
  idci.group_action.registry.class: IDCI\Bundle\GroupActionBundle\Action\GroupActionRegistry
  idci.group_action.guesser.class: IDCI\Bundle\GroupActionBundle\Guesser\GroupActionGuesser
  idci.group_action.class: IDCI\Bundle\GroupActionBundle\Action\AbstractGroupAction
  idci.group_action.form.type.class: IDCI\Bundle\GroupActionBundle\Form\GroupActionType
  idci.group_action.manager.class: IDCI\Bundle\GroupActionBundle\Manager\GroupActionManager
  idci.group_action.twig_extension.class: IDCI\Bundle\GroupActionBundle\Twig\GroupActionExtension

services:

  # Registry
  idci.group_action.registry:
    class: "%idci.group_action.registry.class%"

  # Guesser
  idci.group_action.guesser:
    class: "%idci.group_action.guesser.class%"

  # Action
  idci.group_action:
    abstract: true
    class: "%idci.group_action.class%"
    arguments: [ "@doctrine.orm.entity_manager" ]

  # FormType
  idci.group_action.form.type:
    class: "%idci.group_action.form.type.class%"
    arguments:
      - "@translator"
      - "@idci.group_action.registry"
    tags:
      - { name: form.type, alias: group_action }

  # Manager
  idci.group_action.manager:
    class: "%idci.group_action.manager.class%"
    arguments:
      - "@translator"
      - "@form.factory"
      - "@idci.group_action.registry"
      - "@idci.group_action.guesser"
      - "%idci.group_action.enable_confirmation%"

  # Twig Extension
  idci.group_action.twig_extension:
    class: "%idci.group_action.twig_extension.class%"
    arguments:
        - "@twig"
    public: false
    tags:
        - { name: twig.extension }
