version: "3.3"

services:
  php:
    image: idci-group-action/php:7.2-fpm
    volumes:
      - ./:/var/www/group_action
      - composer:/var/www/.composer
    configs:
      - source: php_config
        target: /usr/local/etc/php/php.ini

volumes:
  composer: ~

configs:
  php_config:
    file: ./config/php.ini